### ISSUE TITLE
to_g2d_texture() is not visible in documentation

### ISSUE THREAD

**Issue by Gnurou** [kaikalii/graphics_buffer#1]
Although the introduction paragraph of this crate advertises the fact that a RenderBuffer can be converted into a G2dTexture and rendered into with piston_window, the to_g2d_texture() method [1] is not present in the crate's documentation, making it necessary to go through the source code in order to discover it. This is probably because the feature is optional, but maybe this can be fixed nonetheless?

[1] https://github.com/kaikalii/graphics_buffer/blob/master/src/lib.rs#L123

**Comment by kaikalii** [comment]
It is indeed because the `piston_window_texture` feature is optional. In my opinion, rustdoc needs some way to properly handle crate features. I cannot make it visible in the docs on docs.rs without making the feature enabled by default, which I don't think is necessary.

The only workaround that I know of is to generate the docs yourself, with the feature turned on.

If you have any recommendations for a better solution, I'm open to suggestions.

**Comment by Gnurou** [comment]
I don't have any better suggestion sadly, and I'm not even very fluent with rustdoc to be honest. I just wanted to check whether this was expected or not.

In that case, how about mentioning to_g2d_texture() explicitly in the default doc? It's not the most elegant, but at least it would allow users interested in the feature to know where to look.

**Comment by kaikalii** [comment]
I've added some documentation for this function that is visible even without the feature flag turned on, so I'll close this issue for now.

**Comment by Gnurou** [comment]
That's perfect, thank you!
